### ISSUE TITLE
Could you adapt the "Files APP" please? 

### ISSUE THREAD

**Issue by Immortal-Sty** [adyanth/QuickLook.Plugin.FolderViewer#10]
"Files APP" is a file explorer. When I set "Files APP" as the default, the plugin still uses windows explorer to open the folder.

We can find "Files APP" in "Microsoft Store".

**Comment by adyanth** [comment]
Explorer (explorer.exe) is called with the file path as the argument. 

How/Where is your app set as default? If it is the registry, that would mean QuickLook would need to muck around in the registry, which might also need Admin rights.

One solution would be to modify the plugin to call the files app instead of explorer, but that won't be sustainable as new file managers come and go. You could fork this, make that change and build it if you really wanted to.

Reference:
https://github.com/adyanth/QuickLook.Plugin.FolderViewer/blob/9b110e7d6976ebf3ded8f1263b997fc854e92093/FileListView.xaml.cs#L81

**Comment by adyanth** [comment]
Looks like it is in the registry. I am not sure what it would imply to read that, or what other apps utilize the same to make use of it.

Reference:
https://github.com/files-community/Files/blob/123f9f31b51fa6b529863edab66c67462c578f46/src/Files.FullTrust/MessageHandlers/Win32MessageHandler.cs#L47
